### ISSUE TITLE
How to associate a Tkinter variable with a label.

### ISSUE THREAD

**Issue by WK-GiHu** [gman2682/school-project#7]
@gman2682 

### Read [How to associate a Tkinter variable with a label.](http://effbot.org/tkinterbook/label.htm)

Look at the definition of `OptionMenu`:
https://github.com/gman2682/school-project/blob/5d916f2a4c150f178b9d6532b6b4f770e6e24360/PayrollCalculator.py#L45
**How ist the option `opt` associated with the function `def calculate`?**

```
def calculate():
    state = opt.get()
    print('state == {}'.format(state))
    tax = states_dict[state]
    print('tax in {} is {}'.format(state, tax))
    salary = (float(hoursWorked.get()) * float(payRate.get())) - (float(payRate.get()) * states_dict[state])
    print('tax in {} is {} result in salary:{}'.format(state, tax, salary))
```

You need the opposite of what you do, to associate the option, choosen in `OptionMenu`, to `.get()` the option value.

**Hint**: A `tk.StringVar` object have methodes to  `.get()` and `.set(...)` values.

**Comment by gman2682** [comment]
Okay, I’ve tried following your directions but salary still is undefined. I updated code for your review

**Comment by WK-GiHu** [comment]
@gman2682 

https://github.com/gman2682/school-project/blob/5244feca663ea7399c092232950d7fb969fa30ad/PayrollCalculator.py#L53

This statement is still wrong, you should see something like this:

    Total Pay: $PY_VAR3

You use the variable `resultsShown` to format a string.
But, the `tk.Label` object have to be **associated** with the variable `resultsShown`.
This allows to update the attribute `text` of object `tk.Label` by doing `resultsShown.set(...)`.
Read again: https://github.com/gman2682/school-project/issues/3#issuecomment-545616116
### Read again: [How to associate a Tkinter variable with a label.](http://effbot.org/tkinterbook/label.htm)

**Comment by WK-GiHu** [comment]
@gman2682 

It seems, you get *How to associate a Tkinter variable with a label.*, `... textvariable=result ...`, we can close this Issue.
